# Generated by Django 4.2.29 on 2026-03-31 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=50, unique=True)),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('conditions', models.TextField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='actif', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Client.client')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Location.location')),
            ],
        ),
    ]
