# Generated by Django 4.2.29 on 2026-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contrat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrat',
            options={'ordering': ['-date_signature'], 'verbose_name': 'Contrat', 'verbose_name_plural': 'Contrats'},
        ),
    ]
