# Generated by Django 4.2.11 on 2026-05-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_alter_location_id'),
        ('Reservation', '0003_alter_reservation_id'),
        ('Contrat', '0003_alter_contrat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Reservation.reservation'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Location.location'),
        ),
    ]
