# Generated by Django 4.2.11 on 2026-05-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assurance', '0001_initial'),
        ('Contrat', '0004_contrat_reservation_alter_contrat_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='assurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='Assurance.assurance'),
        ),
    ]
