# Generated by Django 4.2.29 on 2026-03-31 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Voiture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('activee', 'Activée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('nombre_jours', models.IntegerField()),
                ('prix_estime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Voiture.voiture')),
            ],
        ),
    ]
