# Generated by Django 4.2.29 on 2026-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_reservation'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
    ]
