# Generated by Django 4.2.11 on 2026-05-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0003_alter_reservation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='lieu_arrivee',
            field=models.CharField(default='Casablanca', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lieu_depart',
            field=models.CharField(default='Casablanca', max_length=100),
        ),
    ]
