# Generated by Django 4.2.11 on 2026-05-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assurance', '0001_initial'),
        ('Reservation', '0004_reservation_lieu_arrivee_reservation_lieu_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='assurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assurance.assurance'),
        ),
    ]
