# Generated by Django 4.2.29 on 2026-04-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('idAssurance', models.AutoField(primary_key=True, serialize=False)),
                ('nomAssurance', models.CharField(max_length=100)),
                ('typeAssurance', models.CharField(help_text="Type d'assurance (ex. tous risques, responsabilité civile)", max_length=100)),
                ('prix', models.FloatField()),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
            ],
            options={
                'verbose_name': 'Assurance',
                'verbose_name_plural': 'Assurances',
            },
        ),
    ]
