# Generated by Django 4.2.11 on 2026-05-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='assurances/'),
        ),
    ]
