# Generated by Django 4.2.29 on 2026-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_inscription'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
