# Generated by Django 4.2.11 on 2026-05-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
