# Generated by Django 4.2.29 on 2026-03-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('annee', models.IntegerField()),
                ('prix_par_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('louee', 'Louée'), ('maintenance', 'Maintenance')], default='disponible', max_length=20)),
                ('kilométrage', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
