# Generated by Django 4.2.29 on 2026-04-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Voiture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieVoiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacite_passagers', models.IntegerField(default=5)),
                ('nombre_portes', models.IntegerField(default=4)),
                ('type_carburant', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie Voiture',
                'verbose_name_plural': 'Catégories Voitures',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='voiture',
            options={'ordering': ['marque', 'modele'], 'verbose_name': 'Voiture', 'verbose_name_plural': 'Voitures'},
        ),
        migrations.AddField(
            model_name='voiture',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='voitures', to='Voiture.categorievoiture'),
            preserve_default=False,
        ),
    ]
