# Generated by Django 4.2.29 on 2026-04-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voiture', '0002_categorievoiture_alter_voiture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorievoiture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
