# Generated by Django 4.2.11 on 2026-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voiture', '0004_alter_categorievoiture_id_alter_voiture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='derniere_mise_a_jour_gps',
            field=models.DateTimeField(blank=True, help_text='Dernière mise à jour de la position', null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude actuelle', null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude actuelle', null=True),
        ),
    ]
