# Generated by Django 4.2.11 on 2026-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voiture', '0005_voiture_derniere_mise_a_jour_gps_voiture_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='ville',
            field=models.CharField(default='Casablanca', max_length=100),
        ),
    ]
