# Generated by Django 4.2.29 on 2026-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
