# Generated by Django 4.2.29 on 2026-03-31 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode_paiement', models.CharField(choices=[('carte', 'Carte bancaire'), ('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('refuse', 'Refusé'), ('remboursé', 'Remboursé')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('numero_transaction', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Client.client')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Location.location')),
            ],
        ),
    ]
