# Generated by Django 4.2.11 on 2026-05-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paiement', '0003_alter_paiement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='methode_paiement',
            field=models.CharField(choices=[('carte', 'Carte bancaire'), ('paypal', 'PayPal'), ('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement')], max_length=20),
        ),
    ]
